runtime: go112  # or go113 or go114 for Go 1.13 or Go 1.14 (beta)

instance_class: F2

env_variables:
  MYSQL_DSN: mysql:unix_socket=/cloudsql/cylinder-tracker-282110:us-central1:cylinder-tracker-db;dbname=cylindertracker
  MYSQL_USER: root
  MYSQL_PASSWORD: 123456

handlers:
  - url: /stylesheets
    static_dir: stylesheets

  - url: /(.*\.(gif|png|jpg))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg)$

  - url: /.*
    script: auto

